### ISSUE TITLE
No vehicles found

### ISSUE THREAD

**Issue by francisco-navarro** [Farfar/homeassistant-seatconnect#37]
The integration was working for 2 years, but now I have this problem:

2023-08-30 20:43:21.727 ERROR (MainThread) [seatconnect.connection] Received unhandled error indicating client-side problem.
2023-08-30 20:43:21.738 ERROR (MainThread) [custom_components.seatconnect.config_flow] Fetch vehicles failed with error: No vehicles were found for given account!

**Comment by rliegmann** [comment]
Same here.
I'm afraid Seat/Cupra has changed something again to make life more difficult for us.

**Comment by husel2000** [comment]
Same Problem here, (cupra), mhhh something i can 
`2023-08-30 21:41:56.527 ERROR (MainThread) [seatconnect.connection] Received unhandled error indicating client-side problem.
Restart or try again later.
2023-08-30 21:41:56.552 WARNING (MainThread) [homeassistant.config_entries] Config entry 'VSSxxxxxxxxxxx' for seatconnect integration not ready yet: No vehicles were found for given account!; Retrying in background`

**Comment by erxaz** [comment]
I got the same issue. Been like this for 1-2 days now.

**Comment by metcrl** [comment]
Yes, it happened again.
And I'm afraid that without anyone actively following the code it will be difficult to keep the integration going as it often happens.
The ideal thing would be to follow the development in parallel with the Skoda and/or Volkswagen integration but I don't know if that is possible

**Comment by c0rrre** [comment]
I dont know if it has something to do with this Integration as im currently unable to use the App too

**Comment by erxaz** [comment]
> I dont know if it has something to do with this Integration as im currently unable to use the App too

My SEAT app works without any issues other than being slow as always, so it doesnt seem to be a general issue with the app.

**Comment by MnemoBRMC** [comment]
Similar error here

**Comment by metcrl** [comment]
> I dont know if it has something to do with this Integration as im currently unable to use the App too

Don't think, the Android app works fine

**Comment by ihasen16** [comment]
A mi tampoco me funciona la aplicación

**Comment by JJ-Labs** [comment]
Mismo problema:
Este error se originó a partir de una integración personalizada.

Logger: custom_components.seatconnect.config_flow
Source: custom_components/seatconnect/config_flow.py:113
Integration: Seat Connect (documentation, issues)
First occurred: 11:00:21 (1 occurrences)
Last logged: 11:00:21

Fetch vehicles failed with error: No vehicles were found for given account!

**Comment by Stephan1908** [comment]
Hi,
I have the same Problem...
Greetings

**Comment by MarcFu** [comment]
Hier das gleiche Verhalten.

**Comment by herbod-nl** [comment]
Same here, hope this can be fixed

**Comment by ronald-den-otter** [comment]
No vin found in API helper Cupra Connect 1.19 Test  (seatcupra2)
This is my diag report
a82a41b6-ecdf-4ffd-bf7b-2d1bb11f7d21

**Comment by dnnrwttr** [comment]
Selbes Problem :( - in meinem CUPRA gabs zusätzlich noch ein OTA Update, die Tage - hat das bei euch geholfen oder ggf. sogar den Kram verursacht?

**Comment by rliegmann** [comment]
@soRailicious Bei meinem Leon steht auch ein OCU Update an. Habe es nicht installiert. Denke nicht das das was damit zu tun hat. VW hier mal wieder was an seiner API geändert. Jetzt muss nur noch einer rausfinden was :-)

**Comment by metcrl** [comment]
If anyone who understands anything about it wants to tell us ignorant people if we can help solve the problem please come forward 😁

**Comment by cyriax** [comment]
Maybe a helpful part of the Debug-Log:

Login itself looks okay-ish, data is recieved:
`
2023-09-03 16:48:23.412 DEBUG (MainThread) [seatconnect.connection] Start authorization for user xxxxxxxxxxxx
2023-09-03 16:48:26.518 DEBUG (MainThread) [seatconnect.connection] Found dynamic credentials form, extracting attributes
2023-09-03 16:48:26.518 DEBUG (MainThread) [seatconnect.connection] JSON: {'clientLegalEntityModel': {'clientId': 'xxxxxxxxxxxx@apps_vw-dilab_com', 'clientAppName': 'CUPRA CONNECT App', 'clientAppDisplayName': 'CUPRA CO [.......]
`

Here's the part where something doesn't look that good anymore:
`
2023-09-03 16:48:31.289 DEBUG (MainThread) [seatconnect.connection] Could not get consent information, error 400, message='Bad Request', url=URL('https://profileintegrityservice.apps.emea.vwapps.io/iaa/pic/v1/users/None/check-profile')
2023-09-03 16:48:31.289 DEBUG (MainThread) [seatconnect.connection] Could not retrieve consent information
2023-09-03 16:48:31.289 DEBUG (MainThread) [seatconnect.connection] Client "vwg" token is missing, call to authorize the client..`

Edit: The 400 would at least fit somewhat to the client-side-error:

`elif 400 <= error.status <= 499:
                _LOGGER.error('Received unhandled error indicating client-side problem.\nRestart or try again later.')`

**Comment by ronald-den-otter** [comment]
2023-09-04 08:13:19.107081
Fetching vehicles associated with account.
DEBUG:seatconnect.connection:HTTP POST "https://profileintegrityservice.apps.emea.vwapps.io/iaa/pic/v1/users/None/check-profile"
DEBUG:seatconnect.connection:Could not get consent information, error 400, message='Bad Request', url=URL('https://profileintegrityservice.apps.emea.vwapps.io/iaa/pic/v1/users/None/check-profile')
DEBUG:seatconnect.connection:Could not retrieve consent information
DEBUG:seatconnect.connection:Client "vwg" token is missing, call to authorize the client.
DEBUG:seatconnect.connection:Trying to fetch api tokens.
DEBUG:seatconnect.connection:Verifying token for ha-5a.prd.eu.vwg.vwautocloud.net
DEBUG:seatconnect.connection:Matching ha-5a.prd.eu.vwg.vwautocloud.net against 30e33736-c537-4c72-ab60-74a7b92cfe83@apps_vw-dilab_com
DEBUG:seatconnect.connection:VW-Group API token verified OK.
DEBUG:seatconnect.connection:HTTP GET "https://msg.volkswagen.de/fs-car/usermanagement/users/v1/seat/ES/vehicles"
ERROR:seatconnect.connection:Received unhandled error indicating client-side problem.
Restart or try again later.

I got exactly same message. But I used the seatconnect python library which is used by HomeAssistant too.
FYI: Until one week ago this code used to work without any issues

**Comment by RamBra** [comment]
I removed the car from the integration and I get message  below when I try add the car again:

2023-09-04 12:54:03.477 ERROR (MainThread) [seatconnect.connection] Received unhandled error indicating client-side problem.
Restart or try again later.
2023-09-04 12:54:03.482 ERROR (MainThread) [custom_components.seatconnect.config_flow] Fetch vehicles failed with error: No vehicles were found for given account!
2023-09-04 12:54:03.484 ERROR (MainThread) [aiohttp.server] Error handling request

**Comment by metcrl** [comment]
Same old problem here: https://github.com/Farfar/homeassistant-seatconnect/issues/34

**Comment by timofin** [comment]
same problem
Home Assistant 2023.8.4

**Comment by blackneonreaper** [comment]
It has nothing to do with the homeassistant-seatconnect repo.

Is the underlaying library seatconnect.
We are receiving a 403 when trying to load the vehicles for some reason. I checked the code to the vw and skoda repo but the requests are the same.  I debugged to make sure the access token is provided but that's all correct.

403 = unauthorised so it could just be vw changing some stuff for seat 🤷 

The bad request debug line is a simple mistake but that doesn't solve the issue.
I don't mind making a PR''s but I have not found a solution. I don't know how these guys reverse engineer the app.
Since I have a seat leon phev for the next 2 years i don't mind looking at bugs.

**Comment by ronald-den-otter** [comment]
Look at seatconnect python library.  https://github.com/Farfar/seatconnect/commit/2cc6be04fbd8b5f21cca915e47bad0d97d544dc2
This probably resolves it. 
Appearantly endpoints of API need to be changed
I tested it locally on my Pi for Cupra Formentor and it seems to work

**Comment by blackneonreaper** [comment]
@rliegmann how did you find this change, how do you decompile the APK?
I tried using JADX and sure you can find some stuff including the new domain there is no link to that domain being used.

I also tested it works just fine

For those who cannot wait, you can update the manifest.json in the customer_components/seatconnect
To use my fork git+https://github.com/blackneonreaper/seatconnect.git#seatconnect==1.1.8
Instead of the seatconnect>=1.1.7 Then reboot homeassistant

or just wait.

**Comment by christianschneider89** [comment]
I forgot that I haven't installed git on this server (problem from original post).

Now I get this message:

```
2023-09-05 17:20:29.806 INFO (SyncWorker_9) [homeassistant.util.package] Attempting install of git+https://github.com/blackneonreaper/seatconnect.git#seatconnect==1.1.8
2023-09-05 17:20:33.074 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package git+https://github.com/blackneonreaper/seatconnect.git#seatconnect==1.1.8: error: subprocess-exited-with-error
          from seatconnect.__version__ import __version__ as lib_version
        File "/tmp/pip-req-build-oswxrgoo/seatconnect/__init__.py", line 7, in <module>
          from seatconnect.connection import Connection
        File "/tmp/pip-req-build-oswxrgoo/seatconnect/connection.py", line 23, in <module>

```

Original post:

Do you have an example of the updated manifest.json? When I replace it with your repo I get

`[homeassistant.util.package] Unable to install package git+https://github.com/blackneonreaper/seatconnect.git#seatconnect==1.1.8: ERROR: Error [Errno 2] File not found: 'git' while executing command git version`

**Comment by christianschneider89** [comment]
RESOLVED

When installing manually with `pip install git+https://github.com/blackneonreaper/seatconnect.git#seatconnect==1.1.8` I got this message:
`ModuleNotFoundError: No module named 'bs4'`

After installing bs4 with `python3 -m pip install bs4` the configuration of the integration was sucessful.

**Comment by rliegmann** [comment]
@blackneonreaper https://github.com/TA2k/ioBroker.vw-connect

**Comment by ablivian** [comment]
I've updated today to 1.1.8.
Unfortunately this didn't solve my issue.
I've deleted the integration via HACS and reinstalled it.
Unfortunately, that also didn't solve my issue.
I've deleted the personal info from the logs.
I have a Cupra Leon.

The verification is OK, but there seems to be an issue fetching the vehicle.
Could someone please have a look at it?

2023-09-06 23:24:25.719 DEBUG (MainThread) [custom_components.seatconnect.config_flow] Creating connection to Seat Connect
2023-09-06 23:24:25.721 INFO (MainThread) [seatconnect.connection] Init Seat Connect library, version 1.1.8
2023-09-06 23:24:25.722 DEBUG (MainThread) [seatconnect.connection] Using service https://msg.volkswagen.de
2023-09-06 23:24:25.725 INFO (MainThread) [seatconnect.connection] Initiating new login
2023-09-06 23:24:25.726 DEBUG (MainThread) [seatconnect.connection] Starting authorization process for client seat
2023-09-06 23:24:26.170 DEBUG (MainThread) [seatconnect.connection] Got redirect to signin-service
2023-09-06 23:24:26.230 DEBUG (MainThread) [seatconnect.connection] Start authorization for user karel.vrancken@delta.blue
2023-09-06 23:24:26.381 DEBUG (MainThread) [seatconnect.connection] Found dynamic credentials form, extracting attributes
2023-09-06 23:24:26.382 DEBUG (MainThread) [seatconnect.connection] JSON: {'clientLegalEntityModel': {'clientId': '..........................@apps_vw-dilab_com', 'clientAppName': 'CUPRA CONNECT App', 'clientAppDisplayName': 'CUPRA CONNECT App', 'legalEntityInfo': {'name': 'SEAT & CUPRA', 'shortName': 'SEAT', 'productName': 'SEAT ID & CUPRA ID', 'theme': 'cupra', 'defaultLanguage': 'de', 'termAndConditionsType': 'DEFAULT', 'legalProperties': {'revokeDataContact': 'customercare@seat.es', 'imprintText': 'IMPRINT', 'countryOfJurisdiction': 'DE'}}, 'informalLanguage': False, 'legalEntityCode': 'seat', 'imprintTextKey': 'imprint.link.text'}, 'template': 'loginAuthenticate', 'hmac': '...............................................', 'useClientRendering': True, 'titleKey': 'title.login.password', 'title': None, 'emailPasswordForm': {'@class': 'com.volkswagen.identitykit.signin.domain.model.dto.EmailPasswordForm', 'email': 'MY_EMAILADRES', 'password': None}, 'error': None, 'relayState': '.........................................', 'nextButtonDisabled': False, 'enableNextButtonAfterSeconds': 0, 'postAction': 'login/authenticate', 'identifierUrl': 'login/identifier'}
2023-09-06 23:24:26.382 DEBUG (MainThread) [seatconnect.connection] Finalizing login
2023-09-06 23:24:26.851 DEBUG (MainThread) [seatconnect.connection] Received authorization code, exchange for tokens.
2023-09-06 23:24:27.183 DEBUG (MainThread) [seatconnect.connection] Verifying token for ......................................@apps_vw-dilab_com
2023-09-06 23:24:27.237 DEBUG (MainThread) [seatconnect.connection] Token for seat verified OK.
2023-09-06 23:24:27.715 DEBUG (MainThread) [seatconnect.connection] Request for "https://profileintegrityservice.apps.emea.vwapps.io/iaa/pic/v1/users/.............................../check-profile" returned with status code [200]
2023-09-06 23:24:27.715 DEBUG (MainThread) [seatconnect.connection] Consent returned {'consentInfo': {'mandatoryConsentInfo': [{'id': 'termsOfUse', 'status': 'VALID'}], 'mandatoryFieldsStatus': True, 'mbbIdStatus': True, 'mbbUserId': '..............................', 'missingMandatoryFields': [], 'scopeId': 'commonMandatoryFields', 'spinStatus': True, 'ssoId': '.................................'}}
2023-09-06 23:24:27.715 DEBUG (MainThread) [seatconnect.connection] User consent is valid, no missing information for profile
2023-09-06 23:24:27.716 DEBUG (MainThread) [seatconnect.connection] Client "vwg" token is missing, call to authorize the client.
2023-09-06 23:24:27.716 DEBUG (MainThread) [seatconnect.connection] Trying to fetch api tokens.
2023-09-06 23:24:27.970 DEBUG (MainThread) [seatconnect.connection] Verifying token for ha-5a.prd.eu.vwg.vwautocloud.net
**2023-09-06 23:24:28.017 DEBUG (MainThread) [seatconnect.connection] VW-Group API token verified OK.
2023-09-06 23:24:28.017 ERROR (MainThread) [custom_components.seatconnect.config_flow] Fetch vehicles failed with error: Could not extract sub attribute from token
2023-09-06 23:24:28.020 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):**
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 170, in get
return await super().get(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 96, in get
result = await self._flow_mgr.async_configure(flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 322, in async_configure
raise ValueError(
ValueError: Show progress can only transition to show progress or show progress done.

**Comment by KennethGunther** [comment]
Still error problem with 1.1.8 after reinstallation with Cupra Formentor

**Comment by dferrandizmont** [comment]
> @rliegmann how did you find this change, how do you decompile the APK? I tried using JADX and sure you can find some stuff including the new domain there is no link to that domain being used.
> 
> I also tested it works just fine
> 
> For those who cannot wait, you can update the manifest.json in the customer_components/seatconnect To use my fork git+https://github.com/blackneonreaper/seatconnect.git#seatconnect==1.1.8 Instead of the seatconnect>=1.1.7 Then reboot homeassistant
> 
> or just wait.

**ONLY FOR 1.1.7**

Thanks for the fix, it's working again. Just for all you who don't know how to modify the manifest.json just need to `vim` / `nano` the file and modify the `seatconnect>=1.1.7` and change it to `git+https://github.com/blackneonreaper/seatconnect.git#seatconnect==1.1.8`, this is how it should look like

```
{
    "domain": "seatconnect",
    "name": "Seat Connect",
    "documentation": "https://github.com/farfar/homeassistant-seatconnect/blob/main/README.md",
    "issue_tracker": "https://github.com/farfar/homeassistant-seatconnect/issues",
    "dependencies": [],
    "config_flow": true,
    "codeowners": ["@Farfar"],
    "requirements": [
        "git+https://github.com/blackneonreaper/seatconnect.git#seatconnect==1.1.8",
        "homeassistant>=2021.12.0"
    ],
    "version": "1.1.7",
    "iot_class": "cloud_polling"
}

**Comment by blackneonreaper** [comment]
I think the Pr has been approved by FarFar by now, so you don't need my fork anymore.
I'll leave it for the time until this issue is closed.
vim/nano is possible you can also just install the file editor plugin to homeassistant, and you can do it via the UI.

**Comment by metcrl** [comment]
I tried to replace all files with the new ones, provided by farfar (1.1.8) but the integration still don't work. What do i have to do?

**Comment by Stephan1908** [comment]
Hello,
I updated to 1.1.8 via HACS and adjusted the Manifest.json as described by dferrandizmont. Keep getting an error:

![grafik](https://github.com/Farfar/homeassistant-seatconnect/assets/60405276/f9ccb360-1f0f-4e8e-b5aa-6257c3bd4713)

**Comment by jressel01** [comment]
Have the same
`2023-09-07 08:54:06.990 ERROR (MainThread) [custom_components.seatconnect.config_flow] Fetch vehicles failed with error: Could not extract sub attribute from token
2023-09-07 08:54:06.991 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in get
    return await super().get(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 96, in get
    result = await self._flow_mgr.async_configure(flow_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in async_configure
    raise ValueError(
ValueError: Show progress can only transition to show progress or show progress done.
`

**Comment by novus84** [comment]
This Version messup my Original App. When I force an Update over HA…this the result in the CUPRA app. 

The old one with the Hotfix in the manifest works fine. 

![IMG_2995](https://github.com/Farfar/homeassistant-seatconnect/assets/57588422/c2458a4d-f1e9-48c0-abaa-700ce0f5919f)

**Comment by dferrandizmont** [comment]
> Hello, I updated to 1.1.8 via HACS and adjusted the Manifest.json as described by dferrandizmont. Keep getting an error:
> 
> ![grafik](https://user-images.githubusercontent.com/60405276/266230507-f9ccb360-1f0f-4e8e-b5aa-6257c3bd4713.png)

I'm still on 1.1.7, just modified the manifest.json and restarted the Home Assistant.

**Comment by RamBra** [comment]
Same problem when I try to add my car.
Reinstalled 1.1.8 via HACS and modified the .json file
2023-09-07 10:45:38.483 ERROR (MainThread) [custom_components.seatconnect.config_flow] Fetch vehicles failed with error: Could not extract sub attribute from token
2023-09-07 10:45:38.486 ERROR (MainThread) [aiohttp.server] Error handling request

**Comment by Stephan1908** [comment]
I downgraded to 1.1.7 and then adjusted the manifest. Error remains after restart.

**Comment by novus84** [comment]
> I downgraded to 1.1.7 and then adjusted the manifest. Error remains after restart.

works fine for me!
